#! /usr/bin/env bash

set -e


RUN_COMMAND="gunicorn webapp.app:app --bind $1 --worker-class gevent --access-logfile - --error-logfile - --name `hostname`"


if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
    RUN_COMMAND="${RUN_COMMAND} --reload --timeout 9999"
    RUN_COMMAND="${RUN_COMMAND} --logger-class canonicalwebteam.flask_base.log_utils.GunicornDevLogger"
fi

# if OTEL_SERVICE_NAME is defined, inject OTEL sdk
if [ -n "${OTEL_SERVICE_NAME}" ]; then
    RUN_COMMAND="${RUN_COMMAND} --config observability/observability.gunicorn.conf.py"
fi

${RUN_COMMAND}
