module.exports = {
  "global-nav": "./static/js/src/base/global-nav.js",
  about: "./static/js/src/public/about/index.js",
  docs: "./static/js/src/public/docs/index.js",
  base: "./static/js/src/base/base.js",
  details: "./static/js/src/public/details/index.js",
  details_docs: "./static/js/src/public/details/docs/index.js",
  details_history: "./static/js/src/public/details/history/index.js",
  details_integrate: "./static/js/src/public/details/integrate/index.js",
  details_libraries: "./static/js/src/public/details/libraries/index.js",
  store: "./static/js/src/public/store/index.js",
  list: "./static/js/src/publisher/list-page.js",
  listing: "./static/js/src/publisher/listing-page.js",
  settings: "./static/js/src/publisher/settings.js",
  "highlight-nav": "./static/js/src/libs/highlight-nav.js",
};
