module.exports = {
  docs: "./static/js/src/public/docs/index.js",
  navigation: "./static/js/src/base/navigation/index.ts",
  "docs-side-nav": "./static/js/src/base/docs-side-nav.ts",
  "redirect-docs-url": "./static/js/src/base/redirect-docs-url.ts",
  base: "./static/js/src/base/base.js",
  details: "./static/js/src/public/details/index.ts",
  details_overview: "./static/js/src/public/details/overview/index.js",
  details_docs: "./static/js/src/public/details/docs/index.js",
  details_resources: "./static/js/src/public/details/resources/index.ts",
  details_integrations: "./static/js/src/public/details/integrations/index.tsx",
  "store-details": "./static/js/src/public/store-details/index.js",
  topics: "./static/js/src/public/topics/index.js",
  "highlight-nav": "./static/js/src/libs/highlight-nav.js",
  "highlight-js": "./static/js/src/base/highlight.js",
  "navigation-events": "./static/js/src/public/navigation-events.ts",
  "icon-validator": "./static/js/src/public/icon-validator/index.tsx",
  interfaces: "./static/js/src/interfaces/index.tsx",
  store: "./static/js/src/store/index.tsx",
  publisher: "./static/js/src/publisher-admin/index.tsx",
  "edit-solution": "./static/js/src/solutions/edit-solution.js",
  "register-solution": "./static/js/src/solutions/register-solution.js",
  search: "./static/js/src/search/App.tsx",
};
