module.exports = {
  about: "./static/js/src/public/about/index.js",
  docs: "./static/js/src/public/docs/index.js",
  base: "./static/js/src/base/base.js",
  details: "./static/js/src/public/details/index.js",
  details_overview: "./static/js/src/public/details/overview/index.js",
  details_docs: "./static/js/src/public/details/docs/index.js",
  details_history: "./static/js/src/public/details/history/index.js",
  details_integrate: "./static/js/src/public/details/integrate/index.js",
  store: "./static/js/src/public/store/index.js",
  list: "./static/js/src/publisher/list-page.js",
  listing: "./static/js/src/publisher/listing-page.js",
  publicise: "./static/js/src/publisher/publicise.js",
  settings: "./static/js/src/publisher/settings.js",
  typer: "./static/js/src/libs/typer.js",
  "highlight-nav": "./static/js/src/libs/highlight-nav.js",
  "highlight-js": "./static/js/src/base/highlight.js",
  "navigation-events": "./static/js/src/public/navigation-events.js",
};
