services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - tempo
      - loki
      - prometheus
    networks:
      - observability
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"  # Loki API
    volumes:
      - ./loki/loki.yaml:/etc/loki/local-config.yaml
    networks:
      - observability

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail/promtail.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - observability
    depends_on:
      - loki


  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"  # Tempo UI/query
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"  # Prometheus UI
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - observability

  statsd-exporter:
    image: prom/statsd-exporter:latest
    ports:
      - "9102:9102"  # Prometheus metrics endpoint
      - "9125:9125/udp"  # StatsD endpoint
    networks:
      - observability
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.132.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "4318:4318"  # OTLP HTTP - app on localhost sends traces here
      - "8081:8081"  # Faro reciever
      - "8889:8889"  # Prometheus metrics endpoint
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - tempo
      - prometheus
    networks:
      - observability

networks:
  observability:
    driver: bridge
