domain: charmhub.io

image: prod-comms.docker-registry.canonical.com/charmhub.io

env:
  - name: MAINTENANCE
    configMapKeyRef:
      key: maintenance
      name: charmhub

  - name: SENTRY_DSN
    value: https://6cacb25de947478faeb57f3836da1cf3@sentry.is.canonical.com//24

  - name: SEARCH_API_KEY
    secretKeyRef:
      key: google-custom-search-key
      name: google-api

extraHosts:
  - domain: jujucharms.com

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'charmhub.io' ) {
      rewrite ^ https://charmhub.io$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    if ($host != 'staging.charmhub.io' ) {
      rewrite ^ https://staging.charmhub.io$request_uri? permanent;
    }
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, <https://res.cloudinary.com>; rel=preconnect";
