OPS_BADGES = {
    "charmcraft-elasticsearch": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "charmcraft-graylog": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "charmcraft-prometheus": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "charmcraft-alertmanager": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "charmcraft-grafana": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "postgresql-k8s": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "discourse-charmers-discourse-k8s": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "charmed-osm-mariadb-k8s": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "jenkins-ci-charmers-jenkins-agent": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "containers-metallb-controller": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "containers-metallb-speaker": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "openldap-charmers-openldap": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "mattermost-charmers-mattermost": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": True,
        "charm-library": True,
        "unit-testing": True,
        "high-availability": True,
    },
}
