OPS_BADGES = {
    "mongodb-k8s": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "charmcraft-elasticsearch": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": True,
    },
    "elasticsearch-k8s": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": True,
    },
    "charmcraft-graylog": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": True,
    },
    "graylog-k8s": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": True,
    },
    "charmcraft-prometheus": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "prometheus-k8s": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "charmcraft-alertmanager": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": True,
    },
    "alertmanager-k8s": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": True,
    },
    "charmcraft-grafana": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "grafana-k8s": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "mysql-k8s": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "cassandra-k8s": {
        "detailed-documentation": False,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "postgresql-k8s": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": True,
    },
    "discourse-charmers-discourse-k8s": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "jenkins-ci-charmers-jenkins-agent": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "openldap-charmers-openldap": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "mattermost-charmers-mattermost": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": False,
        "seamless-upgrades": True,
        "unit-testing": True,
        "high-availability": True,
    },
    "hello-kubecon": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": False,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "nginx-ingress-integrator": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "site24x7-exporter-k8s": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
    "telegraf-k8s": {
        "detailed-documentation": True,
        "guaranteed-getting-started": True,
        "secrets-management": True,
        "implements-sidecar-pattern": True,
        "seamless-upgrades": False,
        "unit-testing": True,
        "high-availability": False,
    },
}
