# flake8: noqa

# TODO This list of featured charms is random Once the import is complete we
# should include the actual list of charms.
# And once the API provides featured charms then we should remove this code
FEATURED_CHARMS = [
    {
        "name": "prometheus",
        "display_name": "Prometheus",
        "summary": "Prometheus for Kubernetes clusters",
        "publisher": "metricsmgmt",
        "icon": "https://api.snapcraft.io/api/v1/media/download/charm_ZhkY5AmM2Gncryt3xMkejF4Wyn8lZMSL_icon__dba76c5b8378a96bb711093e2cf55a2dd098f938e9aff22e13403a8e28b87548.png",
        "platform": "kubernetes",
    },
    {
        "name": "postgresql-k8s",
        "display_name": "PostgreSQL K8s",
        "summary": "PostgreSQL charm for Kubernetes deployments.",
        "publisher": "postgresql-charmers",
        "icon": "https://api.snapcraft.io/api/v1/media/download/charm_zDdv4KnGGAGTYSKyvZtmBleis8tLcKii_icon__58a751522b5f0849e40c39418ea99526f731997ae7720636a5881adce75742d7.png",
        "platform": "kubernetes",
    },
    {
        "name": "discourse",
        "display_name": "Discourse",
        "summary": "Discourse bundled for juju-k8s deployment",
        "publisher": "mthaddon",
        "icon": "https://api.snapcraft.io/api/v1/media/download/charm_7uVm0DWuzZ7R2HnZs1HYNyZh4JAO9cmK_icon__4d0b75dcbd9b2876f927b89d9962d7536abc192312058b1c4d2661a88f93fa29.png",
        "platform": "kubernetes",
    },
    {
        "name": "elasticsearch",
        "display_name": "Elasticsearch",
        "summary": "Elasticsearch is the distributed search and analytics engine.",
        "publisher": "lmaas",
        "icon": "https://assets.ubuntu.com/v1/be6eb412-snapcraft-missing-icon.svg",
        "platform": "kubernetes",
    },
    {
        "name": "graylog-k8s",
        "display_name": "Graylog K8s",
        "summary": "Kubernetes charm for Graylog.",
        "publisher": "lmaas",
        "icon": "https://api.snapcraft.io/api/v1/media/download/charm_Cx3p6f5pSUhYCDBDo2vmpA3hxdPIiEof_icon__1796f2cd44163a28257fb1deb9302ea62792c87c4687f6853a58d5c706f0207d.png",
        "platform": "kubernetes",
    },
    {
        "name": "mattermost",
        "display_name": "Mattermost",
        "summary": "This operator charm deploys Mattermost, using a custom-built image, configurable to use with a postgresql backend.",
        "publisher": "mmost",
        "icon": "https://api.snapcraft.io/api/v1/media/download/charm_sssO0EqGsQ1X4cjdpWT3eVZGsqraBj0c_icon__da58ad7ec5670e4564fc5218fba8db7bf0d9b05432247196b07b4900a71bea27.png",
        "platform": "kubernetes",
    },
    {
        "name": "grafana",
        "display_name": "Grafana",
        "summary": "Data vizualization for the charmed LMA stack",
        "publisher": "metricsmgmt",
        "icon": "https://assets.ubuntu.com/v1/be6eb412-snapcraft-missing-icon.svg",
        "platform": "kubernetes",
    },
    {
        "name": "alertmanager",
        "display_name": "AlertManager",
        "summary": "Alert management for charmed LMA stack",
        "publisher": "Canonical",
        "icon": "https://assets.ubuntu.com/v1/be6eb412-snapcraft-missing-icon.svg",
        "platform": "kubernetes",
    },
    {
        "name": "mariadb",
        "display_name": "MariaDB",
        "summary": "Popular, enhanced, drop-in replacement for MySQL",
        "publisher": "osmeng",
        "icon": "https://api.snapcraft.io/api/v1/media/download/charm_tNiFc3ACzOzO0BUJOTSxeAxVue7rUN1c_icon__0d2a05f1616edbed72466b792907f6724b1823d6958bcee47f0fe66c07c46638.png",
        "platform": "kubernetes",
    },
    {
        "name": "mongodb-k8s",
        "display_name": "MongoDB",
        "summary": "MongoDB charm for Kubernetes",
        "publisher": "mgo",
        "icon": "https://api.snapcraft.io/api/v1/media/download/charm_tssr8F68XYBVUiU6QzMs4BZ7JnH5Itm1_icon__dcd4f86fe38ca430e0e2b221c6ea949af2e04778fae4b4b73658dccc09260714.png",
        "platform": "kubernetes",
    },
    {
        "name": "jenkins-agent",
        "display_name": "Jenkins Agent ",
        "summary": "jenkins-agent operator charm",
        "publisher": "thebutler",
        "icon": "https://api.snapcraft.io/api/v1/media/download/charm_6NmjnZdeCSfHart3dYxjiaYc3RXb9CR4_icon__ad7306147e1bb35df0f370bddb0004ad7f25d5477b2ea3aa911a1eec807a2761.png",
        "platform": "kubernetes",
    },
    {
        "name": "metallb-controller",
        "display_name": "Metallb Controller",
        "summary": "MetalLB controller is the cluster-wide component in charge of IP assignments.   ",
        "publisher": "kubrs",
        "icon": "https://assets.ubuntu.com/v1/be6eb412-snapcraft-missing-icon.svg",
        "platform": "kubernetes",
    },
    {
        "name": "metallb-speaker",
        "display_name": "Metallb Speaker",
        "summary": "MetalLB speaker is the per-node daemon that advertises services with assigned IPs.",
        "publisher": "kubrs",
        "icon": "https://assets.ubuntu.com/v1/be6eb412-snapcraft-missing-icon.svg",
        "platform": "kubernetes",
    },
    {
        "name": "openldap",
        "display_name": "Openldap",
        "summary": "This charm provides a basic OpenLDAP server using the SQL backend.",
        "publisher": "idp",
        "icon": "https://assets.ubuntu.com/v1/be6eb412-snapcraft-missing-icon.svg",
        "platform": "kubernetes",
    },
]


COMMANDS_OVERWRITE = {
    "alertmanager": "~charmcraft/alertmanager",
    "bind": "~bind-charmers/bind",
    "charm-k8s-kafka": "~narindergupta/charm-k8s-kafka",
    "charm-k8s-zookeeper": "~narindergupta/charm-k8s-zookeeper",
    "content-cache": "~content-cache-charmers/content-cache-k8s",
    "discourse": "~discourse-charmers/discourse-k8s",
    "elasticsearch": "~charmcraft/elasticsearch",
    "grafana": "~charmcraft/grafana",
    "gunicorn": "~gunicorn-charmers/gunicorn",
    "jenkins-agent": "~jenkins-ci-charmers/jenkins-agent",
    "k8s-cassandra": "~narindergupta/k8s-cassandra",
    "mariadb": "~kubeflow-charmers/mariadb",
    "mattermost": "~mattermost-charmers/mattermost",
    "metallb-controller": "~containers/metallb-controller",
    "metallb-speaker": "~containers/metallb-speaker",
    "mm-pd-bot": "~mm-pd-bot-charmers/mm-pd-bot",
    "openldap": "~openldap-charmers/openldap",
    "postgresql-k8s": "~postgresql-charmers/postgresql-k8s",
    "prometheus": "~charmcraft/prometheus",
    "site24x7-exporter": "~prometheus-site24x7-exporter-charmers/site24x7-exporter",
    "telegraf": "~telegraf-charmers/telegraf-k8s",
    "unifi-poller": "~unifi-poller-charmers/unifi-poller",
    "wordpress": "~wordpress-charmers/wordpress",
    "graylog-k8s": "~charmcraft/graylog",
    "mongodb-k8s": "~charmed-osm/mongodb-k8s",
}
