name: Pack and Publish Charm

on:
  push:
    branches:
      - charming-charmhub # TODO: Change this to main once we are ready to deploy
    paths:
      - 'charm/**'  # Only trigger when changes are made to the ./charm/ directory

env:
  CHARMCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: true

jobs:
  pack-charm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Setup charmcraft
        run: sudo snap install charmcraft --classic --channel=latest/edge

      - name: Fetch libs
        run: |
          cd ./charm 
          charmcraft fetch-libs

      - name: Pack charm
        run: charmcraft pack -v --project-dir ./charm

      - name: Upload charm
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
        run: charmcraft upload ./*.charm

